export const TYPES = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_PRODUCT: "REMOVE_PRODUCT",
    REMOVE_ALL: "REMOVE_ALL_PRODUCTS",
    CLEAR_CART: "CLEAR_CART",
    A_CONFIRMAR: "A_CONFIRMAR",
    CONFIRMADO: "CONFIRMADO"
}